### ISSUE TITLE
Not working with gunicorn as unable to install : flask_mailman

### ISSUE THREAD

**Issue by tnniras** [app-generator/boilerplate-code-flask-dashboard#14]
```
(env) root@localhost:~/neetuApp# gunicorn --bind 0.0.0.0:8001 run:app
[2022-04-07 04:14:41 +0000] [8109] [INFO] Starting gunicorn 19.10.0
[2022-04-07 04:14:41 +0000] [8109] [INFO] Listening at: http://0.0.0.0:8001 (8109)
[2022-04-07 04:14:41 +0000] [8109] [INFO] Using worker: sync
[2022-04-07 04:14:41 +0000] [8113] [INFO] Booting worker with pid: 8113
[2022-04-07 04:14:41 +0000] [8113] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/neetuApp/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/neetuApp/run.py", line 15, in <module>
    from apps.home.models import Data
  File "/root/neetuApp/apps/__init__.py", line 9, in <module>
    from flask_mailman import Mail
ImportError: No module named flask_mailman
[2022-04-07 04:14:41 +0000] [8113] [INFO] Worker exiting (pid: 8113)
[2022-04-07 04:14:41 +0000] [8109] [INFO] Shutting down: Master
[2022-04-07 04:14:41 +0000] [8109] [INFO] Reason: Worker failed to boot.
(env) root@localhost:~/neetuApp#
```

**Comment by app-generator** [comment]
Hello @tnniras, 

This is strange. `Flask-mailman` is saved in the `req.txt` file. 

Please provide more context:

- Docker or manual build? 
- ENV information:
  - OS type / version
  - Python version
  - Steps you follow

**Comment by tnniras** [comment]
- Manual Install 
- OS : Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-169-generic x86_64) (virtualenv)
- Python version 2.7
- Steps: as per README

**Comment by app-generator** [comment]
Hello @tnniras 

Please switch to a Py 3.x `ENV`.  Our products are not supported on Py 2.x

Let us know your progress.

**Comment by tnniras** [comment]
Hello There,

Switched to `Python3.6` and it worked like a charm. Thank you for you support :) 

Thanks,
Tushar
